// Camino a Madrid — practice prompts for voice mode (Claude) and Gliglish roleplay.
// Loaded via <script src="prompts.js"></script>; PROMPTS is read as a global.
// Castilian Spanish (Spain): vosotros, peninsular vocabulary and usage.
const PROMPTS = [
  // ============================================================
  // PHASE 1 — VOICE (rebooting fluency on familiar ground)
  // ============================================================
  {phase: 1, kind: "voice", es: "Describe cómo es un día normal entre semana para ti, desde que te levantas hasta que te acuestas, y explica qué parte del día te gusta más y por qué."},
  {phase: 1, kind: "voice", es: "Cuéntame qué estudias exactamente en la carrera de ingeniería mecánica y explica por qué te decidiste por esa rama y no por otra."},
  {phase: 1, kind: "voice", es: "Explícame en qué consisten tus prácticas en la startup de hardware: qué haces, con quién trabajas y qué es lo que más te está enseñando."},
  {phase: 1, kind: "voice", es: "Háblame de tu familia: quiénes son, a qué se dedican y con quién tienes más confianza, y explica por qué."},
  {phase: 1, kind: "voice", es: "Describe tu piso o tu habitación en Boston con todo detalle y cuenta qué cambiarías si pudieras."},
  {phase: 1, kind: "voice", es: "Cuéntame cómo es la ciudad de Boston para un estudiante: el clima, el transporte, los sitios para salir y lo que más echarías de menos si te fueras."},
  {phase: 1, kind: "voice", es: "Explica qué haces en tu tiempo libre y por qué esos hobbies te enganchan tanto."},
  {phase: 1, kind: "voice", es: "Describe tu comida favorita, cómo se prepara y en qué ocasiones sueles comerla."},
  {phase: 1, kind: "voice", es: "Cuéntame el último viaje que hiciste: adónde fuiste, con quién y qué fue lo mejor y lo peor."},
  {phase: 1, kind: "voice", es: "Explica cómo llevas la organización de los estudios y el trabajo a la vez, y da consejos a alguien que empieza."},
  {phase: 1, kind: "voice", es: "Describe a tu mejor amigo o amiga y explica por qué os lleváis tan bien."},
  {phase: 1, kind: "voice", es: "Cuéntame qué tipo de música te gusta, cómo la descubriste y qué grupos recomiendas."},
  {phase: 1, kind: "voice", es: "Explica un proyecto de la universidad del que estés orgulloso: qué construiste, qué problemas tuviste y cómo los resolviste."},
  {phase: 1, kind: "voice", es: "Describe cómo era tu vida en el instituto y en qué has cambiado desde entonces."},
  {phase: 1, kind: "voice", es: "Cuéntame qué desayunas normalmente y compara el desayuno americano con lo que crees que se desayuna en España."},
  {phase: 1, kind: "voice", es: "Explica por qué decidiste aprender español y qué te gustaría poder hacer con el idioma dentro de un año."},
  {phase: 1, kind: "voice", es: "Describe tu rutina de deporte o ejercicio y explica cómo te hace sentir cuando la sigues y cuando la dejas."},
  {phase: 1, kind: "voice", es: "Cuéntame cómo es un fin de semana típico tuyo y qué te gustaría hacer diferente."},
  {phase: 1, kind: "voice", es: "Explica qué asignatura se te da mejor y cuál se te atraganta, y por qué crees que es así."},
  {phase: 1, kind: "voice", es: "Describe el barrio donde vives ahora: qué hay cerca, cómo es la gente y qué le falta."},
  {phase: 1, kind: "voice", es: "Cuéntame cómo te imaginas tu primer mes en Madrid y qué es lo que más ilusión te hace."},
  {phase: 1, kind: "voice", es: "Explica cómo funciona algo técnico de tu carrera como si se lo contaras a tu abuela, sin tecnicismos."},
  {phase: 1, kind: "voice", es: "Describe una comida familiar que recuerdes con cariño y explica por qué se te quedó grabada."},
  {phase: 1, kind: "voice", es: "Cuéntame qué series o pelis estás viendo últimamente y cuál me recomiendas sin destriparme el final."},
  {phase: 1, kind: "voice", es: "Explica cómo es el transporte público en Boston y compáralo con lo que has oído del metro de Madrid."},
  {phase: 1, kind: "voice", es: "Describe qué tipo de ropa sueles llevar según la estación del año y explica tu estilo."},
  {phase: 1, kind: "voice", es: "Cuéntame cómo conociste a tu grupo de amigos de la universidad y qué soléis hacer juntos."},
  {phase: 1, kind: "voice", es: "Explica qué herramientas o programas usas en tus prácticas y para qué sirven."},
  {phase: 1, kind: "voice", es: "Describe tu lugar favorito para estudiar y explica por qué te concentras mejor allí."},
  {phase: 1, kind: "voice", es: "Cuéntame cómo celebras tu cumpleaños normalmente y cómo sería tu cumpleaños ideal."},
  {phase: 1, kind: "voice", es: "Explica qué haces para desconectar cuando has tenido una semana muy estresante."},
  {phase: 1, kind: "voice", es: "Describe un profesor que te haya marcado y explica qué aprendiste de él o de ella."},
  {phase: 1, kind: "voice", es: "Cuéntame qué se te da bien cocinar y guíame paso a paso por la receta."},
  {phase: 1, kind: "voice", es: "Explica cómo es la relación con tus compañeros de piso o de residencia y qué normas tenéis."},
  {phase: 1, kind: "voice", es: "Describe qué tipo de cafetería te gusta y explica qué pides normalmente."},
  {phase: 1, kind: "voice", es: "Cuéntame un hobby que tuviste de pequeño y que dejaste, y explica por qué lo dejaste."},
  {phase: 1, kind: "voice", es: "Explica qué te motivó a hacer prácticas en una startup pequeña en vez de en una empresa grande."},
  {phase: 1, kind: "voice", es: "Describe cómo es el otoño y el invierno en Boston y cómo te afecta el frío."},
  {phase: 1, kind: "voice", es: "Cuéntame qué planes tienes para las vacaciones de verano y por qué te apetecen."},
  {phase: 1, kind: "voice", es: "Explica cómo organizas el dinero siendo estudiante: en qué gastas y en qué intentas ahorrar."},
  {phase: 1, kind: "voice", es: "Describe tu móvil y las tres aplicaciones que más usas, y explica para qué las usas."},
  {phase: 1, kind: "voice", es: "Cuéntame qué deporte te gusta ver o practicar y explica las reglas básicas a alguien que no lo conoce."},
  {phase: 1, kind: "voice", es: "Explica qué diferencia hay entre cómo estudiabas en el instituto y cómo estudias ahora en la universidad."},
  {phase: 1, kind: "voice", es: "Describe tu coche o el medio de transporte que usas a diario y cuenta alguna anécdota con él."},
  {phase: 1, kind: "voice", es: "Cuéntame qué te gustaría estar haciendo profesionalmente dentro de cinco años y explica el porqué."},
  {phase: 1, kind: "voice", es: "Explica cómo es tu barrio ideal para vivir y compáralo con dónde vives ahora."},

  // ============================================================
  // PHASE 1 — GLIGLISH (café, directions, shopping, introductions, transport)
  // ============================================================
  {phase: 1, kind: "gliglish", es: "Pides algo de beber en un bar y luego pides la cuenta.", frases: "una caña, por favor; ¿me cobras?; para llevar"},
  {phase: 1, kind: "gliglish", es: "Paras a alguien por la calle para preguntar cómo llegar a una boca de metro.", frases: "perdona, ¿para ir a Sol?; ¿está lejos?; ¿voy andando o en metro?"},
  {phase: 1, kind: "gliglish", es: "Compras una prenda de ropa y pides otra talla.", frases: "¿tenéis esto en otra talla?; ¿cuánto cuesta?; me lo llevo"},
  {phase: 1, kind: "gliglish", es: "Te presentas a un compañero de clase nuevo y le preguntas por él.", frases: "hola, me llamo Alex; encantado; soy de Boston"},
  {phase: 1, kind: "gliglish", es: "Le preguntas al conductor del autobús si pasa por tu parada.", frases: "¿este bus va a Atocha?; ¿cuántas paradas son?; ¿me avisas?"},
  {phase: 1, kind: "gliglish", es: "Desayunas en un bar y luego pides la cuenta.", frases: "un café con leche y un croissant; ¿está incluido el desayuno?; la cuenta, por favor"},
  {phase: 1, kind: "gliglish", es: "Preguntas dónde está la estación de metro más cercana.", frases: "perdona, ¿dónde está la parada de metro más cercana?; ¿es esa línea?; gracias"},
  {phase: 1, kind: "gliglish", es: "Te pruebas ropa y le dices al dependiente que no te queda bien.", frases: "quería probarme esto; ¿dónde están los probadores?; me queda un poco grande"},
  {phase: 1, kind: "gliglish", es: "Le pides una recomendación al camarero y haces el pedido.", frases: "¿qué me recomiendas?; ¿lleva algo picante?; para dos personas"},
  {phase: 1, kind: "gliglish", es: "Compras una entrada para un museo y preguntas por el descuento de estudiante.", frases: "una entrada, por favor; ¿hay descuento para estudiantes?; ¿a qué hora abre?"},
  {phase: 1, kind: "gliglish", es: "Pides un zumo en una cafetería y aclaras que lo quieres sin hielo.", frases: "¿me pones un zumo de naranja?; ¿natural?; sin hielo, gracias"},
  {phase: 1, kind: "gliglish", es: "Preguntas por una calle concreta a la que quieres llegar.", frases: "perdone, busco la calle Gran Vía; ¿es la primera a la derecha?; muchas gracias"},
  {phase: 1, kind: "gliglish", es: "Le preguntas a otro pasajero a qué hora pasa el próximo tren.", frases: "¿tienes hora?; ¿el próximo tren a qué hora pasa?; ¿este andén?"},
  {phase: 1, kind: "gliglish", es: "Charlas con alguien que acabas de conocer en una fiesta.", frases: "hola, ¿qué tal?; ¿de dónde eres?; ¿estudias o trabajas?"},
  {phase: 1, kind: "gliglish", es: "Compras fruta en un puesto del mercado.", frases: "¿cuánto vale el kilo?; ponme medio kilo; ¿algo más? no, ya está"},
  {phase: 1, kind: "gliglish", es: "Compras un billete de tren en la estación.", frases: "quería un billete para Barcelona; de ida y vuelta; ¿ventanilla o pasillo?"},
  {phase: 1, kind: "gliglish", es: "Recargas el abono transporte en la máquina y pides ayuda.", frases: "¿me recargas el abono?; treinta días; con tarjeta"},
  {phase: 1, kind: "gliglish", es: "Pides comida para llevar y preguntas cuánto tarda.", frases: "perdona, ¿esto para llevar cuánto tarda?; ¿me lo calientas?; gracias"},
  {phase: 1, kind: "gliglish", es: "Preguntas si una silla está libre en una cafetería llena.", frases: "¿está libre esta silla?; ¿os importa si me siento?; gracias"},
  {phase: 1, kind: "gliglish", es: "Vas a recoger un pedido que hiciste por teléfono.", frases: "hola, vengo a recoger un pedido; a nombre de Alex; ¿es este?"},
  {phase: 1, kind: "gliglish", es: "Preguntas si aceptan tarjeta en una tienda pequeña antes de comprar.", frases: "¿aceptáis tarjeta?; ¿hay mínimo?; entonces pago en efectivo"},
  {phase: 1, kind: "gliglish", es: "Preguntas cómo llegar andando al Retiro y cuánto se tarda.", frases: "¿me indicas cómo llegar al Retiro?; ¿por aquí?; ¿cuánto se tarda andando?"},

  // ============================================================
  // PHASE 2 — VOICE (opinions, debate, hypotheticals, storytelling)
  // ============================================================
  {phase: 2, kind: "voice", es: "Defiende la postura de que los móviles hacen más daño que bien a los estudiantes, aunque no estés del todo de acuerdo."},
  {phase: 2, kind: "voice", es: "Yo voy a decir que la universidad presencial ya no merece la pena. Rebate mi argumento con datos y ejemplos."},
  {phase: 2, kind: "voice", es: "¿Qué harías si te tocara la lotería mañana? Explica qué cambiarías y qué dejarías igual."},
  {phase: 2, kind: "voice", es: "Cuéntame una historia de algo que te salió mal en el pasado y explica qué aprendiste de aquello."},
  {phase: 2, kind: "voice", es: "Debate conmigo esta idea: sería mejor que todo el mundo trabajara cuatro días a la semana. Da argumentos a favor y en contra."},
  {phase: 2, kind: "voice", es: "¿Qué harías si un amigo te pidiera dinero prestado por tercera vez y sospecharas que no te lo va a devolver?"},
  {phase: 2, kind: "voice", es: "Convénceme de que la inteligencia artificial va a mejorar la educación, y luego dime dónde crees que puede ir mal."},
  {phase: 2, kind: "voice", es: "Cuéntame el mejor viaje de tu vida como si fuera una historia, usando el pasado, con principio, nudo y desenlace."},
  {phase: 2, kind: "voice", es: "Voy a defender que las redes sociales deberían prohibirse a los menores de dieciséis años. Llévame la contraria."},
  {phase: 2, kind: "voice", es: "¿Cómo sería tu vida ahora mismo si hubieras estudiado otra carrera completamente distinta?"},
  {phase: 2, kind: "voice", es: "Explica por qué estás de acuerdo o en desacuerdo con que el teletrabajo aísla a la gente, y matiza tu opinión."},
  {phase: 2, kind: "voice", es: "Si pudieras cambiar una sola cosa del sistema universitario, ¿cuál sería y qué consecuencias tendría?"},
  {phase: 2, kind: "voice", es: "Cuéntame una vez que discutiste con alguien y al final le diste la razón, y explica por qué cambiaste de idea."},
  {phase: 2, kind: "voice", es: "Defiende que viajar barato y con mochila enseña más que un viaje organizado de lujo, aunque sea incómodo."},
  {phase: 2, kind: "voice", es: "¿Qué harías si te ofrecieran un trabajo increíble pero en una ciudad donde no conoces a nadie?"},
  {phase: 2, kind: "voice", es: "Discute si es mejor ser generalista o especialista en ingeniería, y hacia cuál tirarías tú."},
  {phase: 2, kind: "voice", es: "Voy a decir que el inglés debería ser la única lengua de la ciencia. Convénceme de que me equivoco."},
  {phase: 2, kind: "voice", es: "Cuéntame una anécdota graciosa que te pasara viajando y que ahora te haga reír aunque en el momento no tuviera gracia."},
  {phase: 2, kind: "voice", es: "Si tuvieras que vivir sin internet durante un mes, ¿cómo lo organizarías y qué echarías más de menos?"},
  {phase: 2, kind: "voice", es: "Explica si crees que las startups explotan a los becarios o les dan oportunidades únicas, y justifícate."},
  {phase: 2, kind: "voice", es: "Defiende una opinión impopular que tengas de verdad y prepárate para que yo te presione con preguntas."},
  {phase: 2, kind: "voice", es: "¿Qué habrías hecho de forma distinta en tu primer año de universidad si volvieras a empezar?"},
  {phase: 2, kind: "voice", es: "Discute si las ciudades deberían prohibir los coches en el centro, pensando en lo bueno y lo malo para la gente."},
  {phase: 2, kind: "voice", es: "Cuéntame la historia de cómo conociste a una persona importante en tu vida, con todos los detalles del momento."},
  {phase: 2, kind: "voice", es: "Voy a defender que estudiar en el extranjero está sobrevalorado. Rebáteme con tu propia experiencia y expectativas."},
  {phase: 2, kind: "voice", es: "Si pudieras hablar con tu yo de hace cinco años, ¿qué le dirías y qué crees que él no querría escuchar?"},
  {phase: 2, kind: "voice", es: "Explica por qué la gente pospone las cosas importantes y da tu teoría sobre cómo se combate la procrastinación."},
  {phase: 2, kind: "voice", es: "Discute si la fama y el dinero cambian a las personas o solo sacan lo que ya llevaban dentro."},
  {phase: 2, kind: "voice", es: "Cuéntame una decisión difícil que tomaste y explica cómo la valoras ahora, con la perspectiva del tiempo."},
  {phase: 2, kind: "voice", es: "Si fueras alcalde de tu ciudad por un día, ¿qué medida tomarías y a quién le sentaría mal?"},
  {phase: 2, kind: "voice", es: "Defiende que a veces mentir es lo más ético, y ponme un ejemplo concreto que me haga dudar."},
  {phase: 2, kind: "voice", es: "Explica cómo cambiaría tu día a día si dejaras de usar el móvil una semana entera, para bien y para mal."},
  {phase: 2, kind: "voice", es: "Voy a decir que la carrera universitaria no sirve para encontrar trabajo. Discute conmigo con ejemplos reales."},
  {phase: 2, kind: "voice", es: "Cuéntame una época de tu vida en la que lo pasaste mal y explica cómo saliste de ella."},
  {phase: 2, kind: "voice", es: "Discute si es mejor tener pocos amigos muy cercanos o muchos conocidos, y qué eliges tú y por qué."},
  {phase: 2, kind: "voice", es: "¿Qué harías si descubrieras que tu empresa de prácticas hace algo que va contra tus principios?"},
  {phase: 2, kind: "voice", es: "Defiende la idea de que el fracaso es más útil que el éxito, y ponme un ejemplo de tu vida."},
  {phase: 2, kind: "voice", es: "Explica si crees que la gente de tu generación tiene más o menos oportunidades que la de tus padres."},
  {phase: 2, kind: "voice", es: "Si tuvieras que convencer a un amigo miedoso de mudarse a otro país, ¿qué argumentos usarías?"},
  {phase: 2, kind: "voice", es: "Cuéntame un malentendido que tuviste con alguien por culpa del idioma o de la cultura."},
  {phase: 2, kind: "voice", es: "Discute si las notas miden de verdad lo que sabe una persona o solo lo bien que memoriza."},
  {phase: 2, kind: "voice", es: "Voy a defender que deberíamos comer mucha menos carne. Llévame la contraria con argumentos serios."},
  {phase: 2, kind: "voice", es: "Si pudieras dominar cualquier habilidad al instante, ¿cuál elegirías y cómo cambiaría tu vida?"},
  {phase: 2, kind: "voice", es: "Cuéntame una promesa que te hiciste a ti mismo y explica si la has cumplido o por qué no."},
  {phase: 2, kind: "voice", es: "Explica por qué crees que a la gente le cuesta tanto cambiar de opinión, aunque le den pruebas."},

  // ============================================================
  // PHASE 2 — GLIGLISH (returns, plans, phone call, doctor, complaint)
  // ============================================================
  {phase: 2, kind: "gliglish", es: "Devuelves algo en una tienda y pides que te lo cambien o te devuelvan el dinero.", frases: "vengo a devolver esto; no me va bien; ¿me lo cambiáis o me devolvéis el dinero?"},
  {phase: 2, kind: "gliglish", es: "Quedas con un amigo para el fin de semana y acordáis hora y sitio.", frases: "¿quedamos el sábado?; ¿te viene bien a las ocho?; ¿dónde te pillo mejor?"},
  {phase: 2, kind: "gliglish", es: "Llamas por teléfono para pedir cita y negocias la hora.", frases: "hola, llamaba para pedir cita; ¿tenéis algo esta semana?; ¿por la tarde?"},
  {phase: 2, kind: "gliglish", es: "Le cuentas tus síntomas al médico y preguntas por el tratamiento.", frases: "me duele la garganta desde hace días; ¿es grave?; ¿me recetas algo?"},
  {phase: 2, kind: "gliglish", es: "Te quejas en un restaurante porque el plato no es lo que habías pedido.", frases: "perdone, esto no es lo que pedí; está frío; ¿me lo cambia, por favor?"},
  {phase: 2, kind: "gliglish", es: "Llamas para anular una reserva y preguntas si hay algún cargo.", frases: "quería anular mi reserva; era para el viernes; ¿hay algún cargo?"},
  {phase: 2, kind: "gliglish", es: "Avisas de que te han cobrado de más y pides que revisen el ticket.", frases: "me han cobrado de más; mira el ticket; ¿me lo puedes revisar?"},
  {phase: 2, kind: "gliglish", es: "Propones cambiar el plan y ofreces una alternativa.", frases: "¿te apetece un plan distinto?; en vez del cine, ¿un tardeo?; tú decides"},
  {phase: 2, kind: "gliglish", es: "Llamas por teléfono y dejas un recado.", frases: "hola, ¿está Marta?; soy Alex; ¿le puedes decir que me llame?"},
  {phase: 2, kind: "gliglish", es: "Devuelves un producto defectuoso que compraste ayer.", frases: "esto vino defectuoso; lo compré ayer; tengo el ticket aquí"},
  {phase: 2, kind: "gliglish", es: "Reservas mesa en un restaurante y pides que sea en la terraza.", frases: "quería reservar mesa para cuatro; para las nueve; en la terraza si puede ser"},
  {phase: 2, kind: "gliglish", es: "Explicas que te encuentras fatal y preguntas si deberías ir a urgencias.", frases: "me encuentro fatal; tengo fiebre; ¿debería ir a urgencias?"},
  {phase: 2, kind: "gliglish", es: "Anulas un plan con educación y lo dejáis para otro día.", frases: "oye, al final no puedo el sábado; ¿lo dejamos para el domingo?; perdona el lío"},
  {phase: 2, kind: "gliglish", es: "Te quejas por la espera y explicas que tienes prisa.", frases: "llevo media hora esperando; ¿tarda mucho?; es que tengo prisa"},
  {phase: 2, kind: "gliglish", es: "Pides información sobre un curso y preguntas cómo apuntarte.", frases: "quería información sobre el curso; ¿cuánto dura?; ¿hay que apuntarse antes?"},
  {phase: 2, kind: "gliglish", es: "Avisas de un problema en la habitación del hotel y pides que lo arreglen.", frases: "la habitación tiene un problema; el aire no funciona; ¿pueden mandar a alguien?"},
  {phase: 2, kind: "gliglish", es: "Invitas a un amigo a un plan de grupo y le explicas cómo se reparte el gasto.", frases: "¿te apuntas al plan?; somos seis; ponemos bote para la cena"},
  {phase: 2, kind: "gliglish", es: "Vas a recoger unos análisis y preguntas cuándo salen el resto de resultados.", frases: "vengo a recoger unos análisis; a mi nombre; ¿cuándo salen los resultados?"},
  {phase: 2, kind: "gliglish", es: "Insistes en una reclamación y pides hablar con el encargado.", frases: "esto está roto; no lo he usado; quiero hablar con el encargado"},
  {phase: 2, kind: "gliglish", es: "Llamas para confirmar la cita que tienes mañana.", frases: "¿me confirmas la cita?; era mañana a las diez; ¿sigue en pie?"},

  // ============================================================
  // PHASE 3 — VOICE (Madrid simulation, bureaucracy, flat life)
  // ============================================================
  {phase: 3, kind: "voice", es: "Narra cómo pides la cita previa en extranjería para el NIE, paso a paso, y explica qué harías si la web no te da hueco."},
  {phase: 3, kind: "voice", es: "Imagina que llegas a la oficina de extranjería y te falta un papel. Cuéntame la conversación con el funcionario y cómo intentas resolverlo."},
  {phase: 3, kind: "voice", es: "Explícale a tu casero que la caldera lleva tres días sin funcionar y convéncele de que mande a alguien esta misma semana."},
  {phase: 3, kind: "voice", es: "Negocia con tus compañeros de piso un reparto justo de las tareas y de los gastos de comunidad, defendiendo tu propuesta."},
  {phase: 3, kind: "voice", es: "Cuéntame cómo organizarías un finde con amigos en Madrid con poco presupuesto, y qué harías si empieza a llover."},
  {phase: 3, kind: "voice", es: "Simula que vas a empadronarte y el funcionario te dice que el contrato de alquiler no vale. Explica cómo reaccionas."},
  {phase: 3, kind: "voice", es: "Explícale a tu compañero de piso, sin montar un pollo, que no ha pagado su parte del alquiler este mes."},
  {phase: 3, kind: "voice", es: "Narra la visita a un piso que quieres alquilar: qué preguntas al casero sobre la fianza, el aval y los gastos."},
  {phase: 3, kind: "voice", es: "Te han subido el alquiler de golpe. Explica cómo hablarías con el casero para negociar o para decidir mudarte."},
  {phase: 3, kind: "voice", es: "Cuenta cómo te darías de alta de la luz y el internet en un piso nuevo y qué harías si te cobran mal la primera factura."},
  {phase: 3, kind: "voice", es: "Simula que llamas al médico de cabecera para pedir cita y te dan una fecha dentro de un mes. Reacciona y busca una solución."},
  {phase: 3, kind: "voice", es: "Explica a un amigo recién llegado cómo funciona el abono transporte y por qué le conviene el abono joven."},
  {phase: 3, kind: "voice", es: "Narra una cena de cañas con compañeros del trabajo en la que tienes que presentarte y encajar en el grupo."},
  {phase: 3, kind: "voice", es: "Tu compañero de piso hace botellón en casa cada finde y tú tienes que madrugar. Explica cómo planteas el problema."},
  {phase: 3, kind: "voice", es: "Simula que vas al banco a abrir una cuenta y te piden un montón de documentos que no llevas. Cuenta cómo lo gestionas."},
  {phase: 3, kind: "voice", es: "Explica cómo reclamarías la devolución de la fianza a un casero que dice que hay desperfectos que tú no hiciste."},
  {phase: 3, kind: "voice", es: "Narra un día en el que se te juntan tres trámites: recoger la TIE, empadronarte y pedir la tarjeta sanitaria."},
  {phase: 3, kind: "voice", es: "Tus compañeros quieren hacer un viaje pero cada uno propone algo distinto. Media entre ellos y propón un plan."},
  {phase: 3, kind: "voice", es: "Simula que te has quedado sin llaves a las dos de la mañana y tienes que apañártelas. Cuenta qué haces."},
  {phase: 3, kind: "voice", es: "Explica cómo le pedirías a tu jefe en las prácticas que te aclare las condiciones de tu nómina y tu horario."},
  {phase: 3, kind: "voice", es: "Narra cómo devolverías un producto en una tienda en la que el dependiente te pone pegas y no quiere aceptarlo."},
  {phase: 3, kind: "voice", es: "Tu vecino se queja del ruido pero tú no habías hecho nada. Explica cómo aclaras el malentendido sin discutir."},
  {phase: 3, kind: "voice", es: "Simula que la agencia inmobiliaria te pide dos meses de fianza y un aval que no tienes. Negocia otra opción."},
  {phase: 3, kind: "voice", es: "Explica cómo organizarías la mudanza a tu piso de Madrid con muebles de segunda mano y sin coche."},
  {phase: 3, kind: "voice", es: "Narra una conversación con un compañero de piso al que le toca fregar y siempre lo deja para otro día."},
  {phase: 3, kind: "voice", es: "Simula que pierdes el metro de vuelta y tienes que decidir entre un taxi caro o esperar el búho. Razona en voz alta."},
  {phase: 3, kind: "voice", es: "Explica cómo pedirías el certificado de empadronamiento por internet y qué harías si la sede electrónica se cae."},
  {phase: 3, kind: "voice", es: "Tus amigos quieren cenar fuera pero tú estás a dos velas hasta fin de mes. Propón un plan más barato sin quedar mal."},
  {phase: 3, kind: "voice", es: "Narra cómo resolverías que te han metido en un grupo de gastos de piso donde alguien no paga nunca."},
  {phase: 3, kind: "voice", es: "Simula una llamada a la compañía de internet porque llevas una semana sin conexión y nadie te da soluciones."},
  {phase: 3, kind: "voice", es: "Explica cómo le contarías a tu familia por videollamada tu primer mes en Madrid, lo bueno y lo que te ha costado."},
  {phase: 3, kind: "voice", es: "Tu casero quiere entrar en el piso sin avisar. Explica cómo le dices, con educación pero firme, que debe avisar antes."},
  {phase: 3, kind: "voice", es: "Narra cómo organizarías una cena en el piso para presentar a tus amigos americanos a tus compañeros españoles."},
  {phase: 3, kind: "voice", es: "Simula que en la oficina de extranjería te mandan de una ventanilla a otra. Cuenta cómo mantienes la calma y lo resuelves."},
  {phase: 3, kind: "voice", es: "Explica cómo negociarías con tus compañeros de piso poner la calefacción, que uno quiere ahorrar y otro pasa frío."},
  {phase: 3, kind: "voice", es: "Narra un finde de puente en el que planeáis una escapada a la sierra y a última hora falla el coche."},
  {phase: 3, kind: "voice", es: "Simula que reclamas en el ayuntamiento porque llevas dos meses esperando el empadronamiento y no te llaman."},
  {phase: 3, kind: "voice", es: "Explica cómo le dirías a un compañero de piso que su pareja prácticamente vive en casa y eso te incomoda."},
  {phase: 3, kind: "voice", es: "Narra cómo devolverías un piso al final del contrato dejándolo todo en orden para recuperar la fianza entera."},
  {phase: 3, kind: "voice", es: "Simula que te equivocas de línea en el metro con prisa y tienes que preguntar y reorganizarte sobre la marcha."},
  {phase: 3, kind: "voice", es: "Explica cómo convencerías a tu casero de que te deje pintar la habitación o poner tus muebles."},
  {phase: 3, kind: "voice", es: "Tus compañeros de piso quieren meter a un cuarto inquilino y a ti no te convence. Defiende tu postura."},
  {phase: 3, kind: "voice", es: "Narra cómo gestionarías que se ha inundado el baño del piso y el casero no coge el teléfono."},
  {phase: 3, kind: "voice", es: "Simula que en el bar te cobran de más en una ronda de cañas para el grupo. Aclara la cuenta sin montar numerito."},
  {phase: 3, kind: "voice", es: "Explica cómo te organizarías para compaginar el curro, las clases de español y la vida social en Madrid sin quemarte."},

  // ============================================================
  // PHASE 3 — GLIGLISH (bureaucracy, flat, bank, bar, SIM, gym, pickup)
  // ============================================================
  {phase: 3, kind: "gliglish", es: "Vas a tu cita de extranjería para el NIE.", frases: "vengo a por la cita del NIE; aquí tiene el justificante; ¿qué documentos faltan?"},
  {phase: 3, kind: "gliglish", es: "Visitas un piso de alquiler y preguntas por la fianza y los gastos.", frases: "quería ver el piso; ¿cuánto es la fianza?; ¿los gastos van aparte?"},
  {phase: 3, kind: "gliglish", es: "Le planteas a tu compañero de piso el problema de la limpieza y propones turnos.", frases: "tenemos que hablar de la limpieza; no me parece justo; propongo turnos"},
  {phase: 3, kind: "gliglish", es: "Abres una cuenta en el banco siendo estudiante extranjero.", frases: "quería abrir una cuenta; soy estudiante extranjero; ¿qué necesito?"},
  {phase: 3, kind: "gliglish", es: "Pides en la barra de un bar con mucho ruido y mucha gente.", frases: "ponme dos cañas y una de bravas; ¿me oyes?; ¿cuánto es?"},
  {phase: 3, kind: "gliglish", es: "Compras una tarjeta SIM y preguntas qué hace falta para contratarla.", frases: "quería una tarjeta SIM; con datos; ¿necesito el pasaporte?"},
  {phase: 3, kind: "gliglish", es: "Te apuntas a un gimnasio y preguntas por la tarifa de estudiante y la permanencia.", frases: "quería apuntarme al gimnasio; ¿hay tarifa de estudiante?; ¿permanencia?"},
  {phase: 3, kind: "gliglish", es: "Recoges un paquete en el punto de recogida.", frases: "vengo a recoger un paquete; aquí está el aviso; mi DNI es este"},
  {phase: 3, kind: "gliglish", es: "Vas al ayuntamiento a empadronarte y pides el certificado.", frases: "vengo a empadronarme; traigo el contrato; ¿me dan el certificado hoy?"},
  {phase: 3, kind: "gliglish", es: "Recargas el abono joven y pides ayuda con la máquina.", frases: "quería recargar el abono joven; treinta días; ¿me ayudas con la máquina?"},
  {phase: 3, kind: "gliglish", es: "Llamas al casero para avisar de que un electrodoméstico está estropeado.", frases: "la nevera hace un ruido raro; lleva días; ¿puede venir el técnico?"},
  {phase: 3, kind: "gliglish", es: "Das de alta la luz a tu nombre en el piso nuevo.", frases: "quería darme de alta de la luz; piso nuevo; ¿cuándo la activáis?"},
  {phase: 3, kind: "gliglish", es: "Preguntas cómo conseguir la tarjeta sanitaria siendo recién llegado.", frases: "necesito pedir cita para la tarjeta sanitaria; soy nuevo aquí; ¿en qué centro?"},
  {phase: 3, kind: "gliglish", es: "Buscas mesa para un grupo y preguntas por el menú del día.", frases: "somos seis para cenar; ¿tenéis mesa?; ¿ponéis menú del día?"},
  {phase: 3, kind: "gliglish", es: "Hablas con tu compañero de piso porque su pareja está en casa todos los días.", frases: "oye, tu pareja está aquí todos los días; no me va bien; hablémoslo"},
  {phase: 3, kind: "gliglish", es: "Reclamas la fianza después de dejar el piso.", frases: "quería reclamar la fianza; dejé el piso bien; ¿cuándo me la devolvéis?"},
  {phase: 3, kind: "gliglish", es: "Te mandan de una ventanilla a otra en una oficina pública y buscas la correcta.", frases: "perdona, ¿este trámite es aquí?; me han mandado de otra ventanilla; ¿número?"},
  {phase: 3, kind: "gliglish", es: "Pides una cerveza y una tapa de pie en la barra.", frases: "quería un doble y una tapa; para la barra; ¿qué tapa entra?"},
  {phase: 3, kind: "gliglish", es: "Llamas a tu compañía porque llevas días sin internet.", frases: "se me ha ido internet; llevo días sin conexión; ¿me mandáis un técnico?"},
  {phase: 3, kind: "gliglish", es: "Devuelves una compra e insistes en que te abonen el dinero.", frases: "quería devolver esto; está sin usar; tengo el ticket; ¿me lo abonáis?"},
  {phase: 3, kind: "gliglish", es: "Llegas a tu cita para la TIE y buscas la cola correcta.", frases: "buenas, tengo cita a las diez; para la TIE; ¿es esta cola?"},
  {phase: 3, kind: "gliglish", es: "Acordáis entre los compañeros de piso cómo repartir los gastos.", frases: "necesitamos repartir los gastos; luz, agua y comunidad; ¿a partes iguales?"},
  {phase: 3, kind: "gliglish", es: "Contratas internet para casa y preguntas cuánto tarda la instalación.", frases: "quería contratar internet para casa; ¿fibra?; ¿cuánto tarda la instalación?"},
  {phase: 3, kind: "gliglish", es: "Pides cambiar de habitación en el piso compartido por el ruido de la calle.", frases: "perdona, ¿me cambias de habitación?; hay mucho ruido; da a la calle"},
  {phase: 3, kind: "gliglish", es: "Intentas pedir cita previa para el NIE y no quedan huecos.", frases: "quería pedir cita previa; para el NIE; ¿no hay huecos?; ¿aviso si sale?"}
];
