// Camino a Madrid — practice prompts for voice mode (Claude) and Gliglish roleplay.
// Loaded via <script src="prompts.js"></script>; PROMPTS is read as a global.
// Castilian Spanish (Spain): vosotros, peninsular vocabulary and usage.
const PROMPTS = [
  // ============================================================
  // PHASE 1 — VOICE (rebooting fluency on familiar ground)
  // ============================================================
  {phase: 1, kind: "voice", es: "Describe cómo es un día normal entre semana para ti, desde que te levantas hasta que te acuestas, y explica qué parte del día te gusta más y por qué.", en: "Describe a normal weekday from waking up to going to bed, and say which part you like most and why."},
  {phase: 1, kind: "voice", es: "Cuéntame qué estudias exactamente en la carrera de ingeniería mecánica y explica por qué te decidiste por esa rama y no por otra.", en: "Explain what you study in mechanical engineering and why you chose that branch."},
  {phase: 1, kind: "voice", es: "Explícame en qué consisten tus prácticas en la startup de hardware: qué haces, con quién trabajas y qué es lo que más te está enseñando.", en: "Explain your internship at the hardware startup: what you do, who you work with, and what you are learning."},
  {phase: 1, kind: "voice", es: "Háblame de tu familia: quiénes son, a qué se dedican y con quién tienes más confianza, y explica por qué.", en: "Talk about your family, what they do, and who you are closest to, and why."},
  {phase: 1, kind: "voice", es: "Describe tu piso o tu habitación en Boston con todo detalle y cuenta qué cambiarías si pudieras.", en: "Describe your flat or room in Boston in detail and what you would change."},
  {phase: 1, kind: "voice", es: "Cuéntame cómo es la ciudad de Boston para un estudiante: el clima, el transporte, los sitios para salir y lo que más echarías de menos si te fueras.", en: "Describe Boston for a student: weather, transport, going out, and what you would miss."},
  {phase: 1, kind: "voice", es: "Explica qué haces en tu tiempo libre y por qué esos hobbies te enganchan tanto.", en: "Explain your hobbies and why they hook you."},
  {phase: 1, kind: "voice", es: "Describe tu comida favorita, cómo se prepara y en qué ocasiones sueles comerla.", en: "Describe your favourite food, how it is made, and when you eat it."},
  {phase: 1, kind: "voice", es: "Cuéntame el último viaje que hiciste: adónde fuiste, con quién y qué fue lo mejor y lo peor.", en: "Tell me about your last trip: where, with whom, best and worst parts."},
  {phase: 1, kind: "voice", es: "Explica cómo llevas la organización de los estudios y el trabajo a la vez, y da consejos a alguien que empieza.", en: "Explain how you juggle studies and work, and give advice to a beginner."},
  {phase: 1, kind: "voice", es: "Describe a tu mejor amigo o amiga y explica por qué os lleváis tan bien.", en: "Describe your best friend and why you get on so well."},
  {phase: 1, kind: "voice", es: "Cuéntame qué tipo de música te gusta, cómo la descubriste y qué grupos recomiendas.", en: "Tell me what music you like, how you found it, and what you recommend."},
  {phase: 1, kind: "voice", es: "Explica un proyecto de la universidad del que estés orgulloso: qué construiste, qué problemas tuviste y cómo los resolviste.", en: "Explain a uni project you are proud of, the problems, and how you solved them."},
  {phase: 1, kind: "voice", es: "Describe cómo era tu vida en el instituto y en qué has cambiado desde entonces.", en: "Describe your high-school life and how you have changed since."},
  {phase: 1, kind: "voice", es: "Cuéntame qué desayunas normalmente y compara el desayuno americano con lo que crees que se desayuna en España.", en: "Describe your usual breakfast and compare it with a Spanish breakfast."},
  {phase: 1, kind: "voice", es: "Explica por qué decidiste aprender español y qué te gustaría poder hacer con el idioma dentro de un año.", en: "Explain why you are learning Spanish and what you want to do with it in a year."},
  {phase: 1, kind: "voice", es: "Describe tu rutina de deporte o ejercicio y explica cómo te hace sentir cuando la sigues y cuando la dejas.", en: "Describe your exercise routine and how it makes you feel."},
  {phase: 1, kind: "voice", es: "Cuéntame cómo es un fin de semana típico tuyo y qué te gustaría hacer diferente.", en: "Describe a typical weekend and what you would do differently."},
  {phase: 1, kind: "voice", es: "Explica qué asignatura se te da mejor y cuál se te atraganta, y por qué crees que es así.", en: "Explain which subject you are best at and which one is hard, and why."},
  {phase: 1, kind: "voice", es: "Describe el barrio donde vives ahora: qué hay cerca, cómo es la gente y qué le falta.", en: "Describe your current neighbourhood: what is nearby, the people, what it lacks."},
  {phase: 1, kind: "voice", es: "Cuéntame cómo te imaginas tu primer mes en Madrid y qué es lo que más ilusión te hace.", en: "Describe how you imagine your first month in Madrid and what excites you most."},
  {phase: 1, kind: "voice", es: "Explica cómo funciona algo técnico de tu carrera como si se lo contaras a tu abuela, sin tecnicismos.", en: "Explain something technical from your field to your grandmother, no jargon."},
  {phase: 1, kind: "voice", es: "Describe una comida familiar que recuerdes con cariño y explica por qué se te quedó grabada.", en: "Describe a family meal you remember fondly and why it stuck with you."},
  {phase: 1, kind: "voice", es: "Cuéntame qué series o pelis estás viendo últimamente y cuál me recomiendas sin destriparme el final.", en: "Tell me what you are watching lately and recommend one without spoilers."},
  {phase: 1, kind: "voice", es: "Explica cómo es el transporte público en Boston y compáralo con lo que has oído del metro de Madrid.", en: "Explain Boston public transport and compare it with the Madrid metro."},
  {phase: 1, kind: "voice", es: "Describe qué tipo de ropa sueles llevar según la estación del año y explica tu estilo.", en: "Describe what you wear by season and explain your style."},
  {phase: 1, kind: "voice", es: "Cuéntame cómo conociste a tu grupo de amigos de la universidad y qué soléis hacer juntos.", en: "Tell me how you met your uni friends and what you do together."},
  {phase: 1, kind: "voice", es: "Explica qué herramientas o programas usas en tus prácticas y para qué sirven.", en: "Explain the tools or software you use at your internship and what they are for."},
  {phase: 1, kind: "voice", es: "Describe tu lugar favorito para estudiar y explica por qué te concentras mejor allí.", en: "Describe your favourite place to study and why you focus there."},
  {phase: 1, kind: "voice", es: "Cuéntame cómo celebras tu cumpleaños normalmente y cómo sería tu cumpleaños ideal.", en: "Describe how you usually celebrate your birthday and your ideal one."},
  {phase: 1, kind: "voice", es: "Explica qué haces para desconectar cuando has tenido una semana muy estresante.", en: "Explain how you unwind after a very stressful week."},
  {phase: 1, kind: "voice", es: "Describe un profesor que te haya marcado y explica qué aprendiste de él o de ella.", en: "Describe a teacher who influenced you and what you learned."},
  {phase: 1, kind: "voice", es: "Cuéntame qué se te da bien cocinar y guíame paso a paso por la receta.", en: "Tell me what you can cook well and walk me through the recipe."},
  {phase: 1, kind: "voice", es: "Explica cómo es la relación con tus compañeros de piso o de residencia y qué normas tenéis.", en: "Explain your relationship with flatmates and the rules you have."},
  {phase: 1, kind: "voice", es: "Describe qué tipo de cafetería te gusta y explica qué pides normalmente.", en: "Describe the kind of café you like and what you usually order."},
  {phase: 1, kind: "voice", es: "Cuéntame un hobby que tuviste de pequeño y que dejaste, y explica por qué lo dejaste.", en: "Tell me about a childhood hobby you dropped and why."},
  {phase: 1, kind: "voice", es: "Explica qué te motivó a hacer prácticas en una startup pequeña en vez de en una empresa grande.", en: "Explain why you chose a small startup over a big company for your internship."},
  {phase: 1, kind: "voice", es: "Describe cómo es el otoño y el invierno en Boston y cómo te afecta el frío.", en: "Describe autumn and winter in Boston and how the cold affects you."},
  {phase: 1, kind: "voice", es: "Cuéntame qué planes tienes para las vacaciones de verano y por qué te apetecen.", en: "Tell me your summer plans and why they appeal to you."},
  {phase: 1, kind: "voice", es: "Explica cómo organizas el dinero siendo estudiante: en qué gastas y en qué intentas ahorrar.", en: "Explain how you manage money as a student: spending and saving."},
  {phase: 1, kind: "voice", es: "Describe tu móvil y las tres aplicaciones que más usas, y explica para qué las usas.", en: "Describe your phone and the three apps you use most, and why."},
  {phase: 1, kind: "voice", es: "Cuéntame qué deporte te gusta ver o practicar y explica las reglas básicas a alguien que no lo conoce.", en: "Tell me a sport you like and explain the basic rules to a newcomer."},
  {phase: 1, kind: "voice", es: "Explica qué diferencia hay entre cómo estudiabas en el instituto y cómo estudias ahora en la universidad.", en: "Explain the difference between how you studied in high school and now."},
  {phase: 1, kind: "voice", es: "Describe tu coche o el medio de transporte que usas a diario y cuenta alguna anécdota con él.", en: "Describe your car or daily transport and share an anecdote."},
  {phase: 1, kind: "voice", es: "Cuéntame qué te gustaría estar haciendo profesionalmente dentro de cinco años y explica el porqué.", en: "Tell me what you want to be doing professionally in five years and why."},
  {phase: 1, kind: "voice", es: "Explica cómo es tu barrio ideal para vivir y compáralo con dónde vives ahora.", en: "Explain your ideal neighbourhood and compare it with where you live now."},

  // ============================================================
  // PHASE 1 — GLIGLISH (café, directions, shopping, introductions, transport)
  // ============================================================
  {phase: 1, kind: "gliglish", es: "una caña, por favor; ¿me cobras?; para llevar", en: "Order a drink at a café and ask for the bill."},
  {phase: 1, kind: "gliglish", es: "perdona, ¿para ir a Sol?; ¿está lejos?; ¿voy andando o en metro?", en: "Ask a stranger for directions to a metro stop."},
  {phase: 1, kind: "gliglish", es: "¿tenéis esto en otra talla?; ¿cuánto cuesta?; me lo llevo", en: "Buy an item of clothing and ask for a different size."},
  {phase: 1, kind: "gliglish", es: "hola, me llamo Alex; encantado; soy de Boston", en: "Introduce yourself to a new classmate and ask about them."},
  {phase: 1, kind: "gliglish", es: "¿este bus va a Atocha?; ¿cuántas paradas son?; ¿me avisas?", en: "Ask the bus driver if the bus goes to your stop."},
  {phase: 1, kind: "gliglish", es: "un café con leche y un croissant; ¿está incluido el desayuno?; la cuenta, por favor", en: "Order breakfast at a bar and ask for the bill."},
  {phase: 1, kind: "gliglish", es: "perdona, ¿dónde está la parada de metro más cercana?; ¿es esa línea?; gracias", en: "Ask where the nearest metro station is."},
  {phase: 1, kind: "gliglish", es: "quería probarme esto; ¿dónde están los probadores?; me queda un poco grande", en: "Try on clothes and tell the shop assistant it does not fit."},
  {phase: 1, kind: "gliglish", es: "¿qué me recomiendas?; ¿lleva algo picante?; para dos personas", en: "Ask a waiter for a recommendation and order."},
  {phase: 1, kind: "gliglish", es: "una entrada, por favor; ¿hay descuento para estudiantes?; ¿a qué hora abre?", en: "Buy a museum ticket and ask about the student discount."},
  {phase: 1, kind: "gliglish", es: "¿me pones un zumo de naranja?; ¿natural?; sin hielo, gracias", en: "Order a juice at a café and specify no ice."},
  {phase: 1, kind: "gliglish", es: "perdone, busco la calle Gran Vía; ¿es la primera a la derecha?; muchas gracias", en: "Ask for directions to a specific street."},
  {phase: 1, kind: "gliglish", es: "¿tienes hora?; ¿el próximo tren a qué hora pasa?; ¿este andén?", en: "Ask another passenger about the next train."},
  {phase: 1, kind: "gliglish", es: "hola, ¿qué tal?; ¿de dónde eres?; ¿estudias o trabajas?", en: "Make small talk with someone at a party."},
  {phase: 1, kind: "gliglish", es: "¿cuánto vale el kilo?; ponme medio kilo; ¿algo más? no, ya está", en: "Buy fruit at a market stall."},
  {phase: 1, kind: "gliglish", es: "quería un billete para Barcelona; de ida y vuelta; ¿ventanilla o pasillo?", en: "Buy a train ticket at the station."},
  {phase: 1, kind: "gliglish", es: "¿me recargas el abono?; treinta días; con tarjeta", en: "Top up your transport pass at a machine and ask for help."},
  {phase: 1, kind: "gliglish", es: "perdona, ¿esto para llevar cuánto tarda?; ¿me lo calientas?; gracias", en: "Order takeaway and ask how long it takes."},
  {phase: 1, kind: "gliglish", es: "¿está libre esta silla?; ¿os importa si me siento?; gracias", en: "Ask if a seat is free in a busy café."},
  {phase: 1, kind: "gliglish", es: "hola, vengo a recoger un pedido; a nombre de Alex; ¿es este?", en: "Pick up an order you placed by phone."},
  {phase: 1, kind: "gliglish", es: "¿aceptáis tarjeta?; ¿hay mínimo?; entonces pago en efectivo", en: "Ask if a small shop takes card before buying."},
  {phase: 1, kind: "gliglish", es: "¿me indicas cómo llegar al Retiro?; ¿por aquí?; ¿cuánto se tarda andando?", en: "Ask how to walk to a park and how long it takes."},

  // ============================================================
  // PHASE 2 — VOICE (opinions, debate, hypotheticals, storytelling)
  // ============================================================
  {phase: 2, kind: "voice", es: "Defiende la postura de que los móviles hacen más daño que bien a los estudiantes, aunque no estés del todo de acuerdo.", en: "Defend the view that phones harm students more than they help, even if you disagree."},
  {phase: 2, kind: "voice", es: "Yo voy a decir que la universidad presencial ya no merece la pena. Rebate mi argumento con datos y ejemplos.", en: "I will argue in-person university is not worth it. Rebut me with evidence."},
  {phase: 2, kind: "voice", es: "¿Qué harías si te tocara la lotería mañana? Explica qué cambiarías y qué dejarías igual.", en: "What would you do if you won the lottery? What would change and stay the same?"},
  {phase: 2, kind: "voice", es: "Cuéntame una historia de algo que te salió mal en el pasado y explica qué aprendiste de aquello.", en: "Tell a story of something that went wrong and what you learned."},
  {phase: 2, kind: "voice", es: "Debate conmigo esta idea: sería mejor que todo el mundo trabajara cuatro días a la semana. Da argumentos a favor y en contra.", en: "Debate a four-day work week, arguing both sides."},
  {phase: 2, kind: "voice", es: "¿Qué harías si un amigo te pidiera dinero prestado por tercera vez y sospecharas que no te lo va a devolver?", en: "What would you do if a friend asked to borrow money a third time?"},
  {phase: 2, kind: "voice", es: "Convénceme de que la inteligencia artificial va a mejorar la educación, y luego dime dónde crees que puede ir mal.", en: "Convince me AI will improve education, then say where it could go wrong."},
  {phase: 2, kind: "voice", es: "Cuéntame el mejor viaje de tu vida como si fuera una historia, usando el pasado, con principio, nudo y desenlace.", en: "Tell your best trip as a full story in the past tense."},
  {phase: 2, kind: "voice", es: "Voy a defender que las redes sociales deberían prohibirse a los menores de dieciséis años. Llévame la contraria.", en: "I will argue for banning social media under 16. Argue against me."},
  {phase: 2, kind: "voice", es: "¿Cómo sería tu vida ahora mismo si hubieras estudiado otra carrera completamente distinta?", en: "How would your life be now if you had studied a different degree?"},
  {phase: 2, kind: "voice", es: "Explica por qué estás de acuerdo o en desacuerdo con que el teletrabajo aísla a la gente, y matiza tu opinión.", en: "Agree or disagree that remote work isolates people, with nuance."},
  {phase: 2, kind: "voice", es: "Si pudieras cambiar una sola cosa del sistema universitario, ¿cuál sería y qué consecuencias tendría?", en: "If you could change one thing about university, what and what consequences?"},
  {phase: 2, kind: "voice", es: "Cuéntame una vez que discutiste con alguien y al final le diste la razón, y explica por qué cambiaste de idea.", en: "Tell of an argument where you ended up agreeing, and why you changed."},
  {phase: 2, kind: "voice", es: "Defiende que viajar barato y con mochila enseña más que un viaje organizado de lujo, aunque sea incómodo.", en: "Argue that backpacking teaches more than a luxury package trip."},
  {phase: 2, kind: "voice", es: "¿Qué harías si te ofrecieran un trabajo increíble pero en una ciudad donde no conoces a nadie?", en: "What would you do if offered a great job in a city where you know no one?"},
  {phase: 2, kind: "voice", es: "Discute si es mejor ser generalista o especialista en ingeniería, y hacia cuál tirarías tú.", en: "Debate generalist vs specialist in engineering and your own leaning."},
  {phase: 2, kind: "voice", es: "Voy a decir que el inglés debería ser la única lengua de la ciencia. Convénceme de que me equivoco.", en: "I will argue English should be the only language of science. Prove me wrong."},
  {phase: 2, kind: "voice", es: "Cuéntame una anécdota graciosa que te pasara viajando y que ahora te haga reír aunque en el momento no tuviera gracia.", en: "Tell a funny travel anecdote that was not funny at the time."},
  {phase: 2, kind: "voice", es: "Si tuvieras que vivir sin internet durante un mes, ¿cómo lo organizarías y qué echarías más de menos?", en: "If you lived a month without internet, how would you cope and what would you miss?"},
  {phase: 2, kind: "voice", es: "Explica si crees que las startups explotan a los becarios o les dan oportunidades únicas, y justifícate.", en: "Do startups exploit interns or give unique chances? Justify your view."},
  {phase: 2, kind: "voice", es: "Defiende una opinión impopular que tengas de verdad y prepárate para que yo te presione con preguntas.", en: "Defend a genuinely unpopular opinion while I push back."},
  {phase: 2, kind: "voice", es: "¿Qué habrías hecho de forma distinta en tu primer año de universidad si volvieras a empezar?", en: "What would you do differently in your first year of uni?"},
  {phase: 2, kind: "voice", es: "Discute si las ciudades deberían prohibir los coches en el centro, pensando en lo bueno y lo malo para la gente.", en: "Debate banning cars in city centres, weighing pros and cons."},
  {phase: 2, kind: "voice", es: "Cuéntame la historia de cómo conociste a una persona importante en tu vida, con todos los detalles del momento.", en: "Tell the story of how you met an important person in your life."},
  {phase: 2, kind: "voice", es: "Voy a defender que estudiar en el extranjero está sobrevalorado. Rebáteme con tu propia experiencia y expectativas.", en: "I will argue studying abroad is overrated. Rebut me."},
  {phase: 2, kind: "voice", es: "Si pudieras hablar con tu yo de hace cinco años, ¿qué le dirías y qué crees que él no querría escuchar?", en: "What would you tell your self of five years ago, and what would he resist?"},
  {phase: 2, kind: "voice", es: "Explica por qué la gente pospone las cosas importantes y da tu teoría sobre cómo se combate la procrastinación.", en: "Explain why people procrastinate and your theory on fighting it."},
  {phase: 2, kind: "voice", es: "Discute si la fama y el dinero cambian a las personas o solo sacan lo que ya llevaban dentro.", en: "Debate whether fame and money change people or reveal them."},
  {phase: 2, kind: "voice", es: "Cuéntame una decisión difícil que tomaste y explica cómo la valoras ahora, con la perspectiva del tiempo.", en: "Tell of a hard decision and how you judge it now."},
  {phase: 2, kind: "voice", es: "Si fueras alcalde de tu ciudad por un día, ¿qué medida tomarías y a quién le sentaría mal?", en: "If you were mayor for a day, what would you do and who would dislike it?"},
  {phase: 2, kind: "voice", es: "Defiende que a veces mentir es lo más ético, y ponme un ejemplo concreto que me haga dudar.", en: "Argue that sometimes lying is most ethical, with a concrete example."},
  {phase: 2, kind: "voice", es: "Explica cómo cambiaría tu día a día si dejaras de usar el móvil una semana entera, para bien y para mal.", en: "Explain how a phone-free week would change your days, good and bad."},
  {phase: 2, kind: "voice", es: "Voy a decir que la carrera universitaria no sirve para encontrar trabajo. Discute conmigo con ejemplos reales.", en: "I will argue degrees do not help you find work. Debate me with examples."},
  {phase: 2, kind: "voice", es: "Cuéntame una época de tu vida en la que lo pasaste mal y explica cómo saliste de ella.", en: "Tell of a hard period and how you got out of it."},
  {phase: 2, kind: "voice", es: "Discute si es mejor tener pocos amigos muy cercanos o muchos conocidos, y qué eliges tú y por qué.", en: "Debate few close friends vs many acquaintances, and your choice."},
  {phase: 2, kind: "voice", es: "¿Qué harías si descubrieras que tu empresa de prácticas hace algo que va contra tus principios?", en: "What would you do if your internship company acted against your principles?"},
  {phase: 2, kind: "voice", es: "Defiende la idea de que el fracaso es más útil que el éxito, y ponme un ejemplo de tu vida.", en: "Argue failure is more useful than success, with a personal example."},
  {phase: 2, kind: "voice", es: "Explica si crees que la gente de tu generación tiene más o menos oportunidades que la de tus padres.", en: "Does your generation have more or fewer chances than your parents?"},
  {phase: 2, kind: "voice", es: "Si tuvieras que convencer a un amigo miedoso de mudarse a otro país, ¿qué argumentos usarías?", en: "How would you convince a fearful friend to move abroad?"},
  {phase: 2, kind: "voice", es: "Cuéntame un malentendido que tuviste con alguien por culpa del idioma o de la cultura.", en: "Tell of a misunderstanding caused by language or culture."},
  {phase: 2, kind: "voice", es: "Discute si las notas miden de verdad lo que sabe una persona o solo lo bien que memoriza.", en: "Debate whether grades measure knowledge or memorisation."},
  {phase: 2, kind: "voice", es: "Voy a defender que deberíamos comer mucha menos carne. Llévame la contraria con argumentos serios.", en: "I will argue we should eat far less meat. Argue against me seriously."},
  {phase: 2, kind: "voice", es: "Si pudieras dominar cualquier habilidad al instante, ¿cuál elegirías y cómo cambiaría tu vida?", en: "If you could master any skill instantly, which and how would life change?"},
  {phase: 2, kind: "voice", es: "Cuéntame una promesa que te hiciste a ti mismo y explica si la has cumplido o por qué no.", en: "Tell of a promise to yourself and whether you kept it."},
  {phase: 2, kind: "voice", es: "Explica por qué crees que a la gente le cuesta tanto cambiar de opinión, aunque le den pruebas.", en: "Explain why people struggle to change their minds despite evidence."},

  // ============================================================
  // PHASE 2 — GLIGLISH (returns, plans, phone call, doctor, complaint)
  // ============================================================
  {phase: 2, kind: "gliglish", es: "vengo a devolver esto; no me va bien; ¿me lo cambiáis o me devolvéis el dinero?", en: "Return an item to a shop and ask for a refund or exchange."},
  {phase: 2, kind: "gliglish", es: "¿quedamos el sábado?; ¿te viene bien a las ocho?; ¿dónde te pillo mejor?", en: "Make weekend plans with a friend and settle on a time and place."},
  {phase: 2, kind: "gliglish", es: "hola, llamaba para pedir cita; ¿tenéis algo esta semana?; ¿por la tarde?", en: "Call to book an appointment and negotiate a time."},
  {phase: 2, kind: "gliglish", es: "me duele la garganta desde hace días; ¿es grave?; ¿me recetas algo?", en: "Describe symptoms at a doctor visit and ask about treatment."},
  {phase: 2, kind: "gliglish", es: "perdone, esto no es lo que pedí; está frío; ¿me lo cambia, por favor?", en: "Complain about your dish at a restaurant and ask for a fix."},
  {phase: 2, kind: "gliglish", es: "quería anular mi reserva; era para el viernes; ¿hay algún cargo?", en: "Call to cancel a reservation and ask about charges."},
  {phase: 2, kind: "gliglish", es: "me han cobrado de más; mira el ticket; ¿me lo puedes revisar?", en: "Point out you were overcharged and ask them to check the receipt."},
  {phase: 2, kind: "gliglish", es: "¿te apetece un plan distinto?; en vez del cine, ¿un tardeo?; tú decides", en: "Suggest changing plans and offer an alternative."},
  {phase: 2, kind: "gliglish", es: "hola, ¿está Marta?; soy Alex; ¿le puedes decir que me llame?", en: "Make a phone call and leave a message."},
  {phase: 2, kind: "gliglish", es: "esto vino defectuoso; lo compré ayer; tengo el ticket aquí", en: "Return a faulty product bought the day before."},
  {phase: 2, kind: "gliglish", es: "quería reservar mesa para cuatro; para las nueve; en la terraza si puede ser", en: "Book a restaurant table and request the terrace."},
  {phase: 2, kind: "gliglish", es: "me encuentro fatal; tengo fiebre; ¿debería ir a urgencias?", en: "Explain you feel very ill and ask whether to go to A and E."},
  {phase: 2, kind: "gliglish", es: "oye, al final no puedo el sábado; ¿lo dejamos para el domingo?; perdona el lío", en: "Cancel plans politely and reschedule."},
  {phase: 2, kind: "gliglish", es: "llevo media hora esperando; ¿tarda mucho?; es que tengo prisa", en: "Complain about a long wait and explain you are in a hurry."},
  {phase: 2, kind: "gliglish", es: "quería información sobre el curso; ¿cuánto dura?; ¿hay que apuntarse antes?", en: "Ask for information about a course and how to enroll."},
  {phase: 2, kind: "gliglish", es: "la habitación tiene un problema; el aire no funciona; ¿pueden mandar a alguien?", en: "Report a hotel room problem and ask for help."},
  {phase: 2, kind: "gliglish", es: "¿te apuntas al plan?; somos seis; ponemos bote para la cena", en: "Invite a friend to a group plan and explain the split cost."},
  {phase: 2, kind: "gliglish", es: "vengo a recoger unos análisis; a mi nombre; ¿cuándo salen los resultados?", en: "Pick up medical test results and ask when more are ready."},
  {phase: 2, kind: "gliglish", es: "esto está roto; no lo he usado; quiero hablar con el encargado", en: "Escalate a complaint and ask to speak to the manager."},
  {phase: 2, kind: "gliglish", es: "¿me confirmas la cita?; era mañana a las diez; ¿sigue en pie?", en: "Call to confirm an appointment for the next day."},

  // ============================================================
  // PHASE 3 — VOICE (Madrid simulation, bureaucracy, flat life)
  // ============================================================
  {phase: 3, kind: "voice", es: "Narra cómo pides la cita previa en extranjería para el NIE, paso a paso, y explica qué harías si la web no te da hueco.", en: "Narrate booking the NIE appointment step by step, and what to do if no slots appear."},
  {phase: 3, kind: "voice", es: "Imagina que llegas a la oficina de extranjería y te falta un papel. Cuéntame la conversación con el funcionario y cómo intentas resolverlo.", en: "You are missing a document at the immigration office. Narrate the conversation."},
  {phase: 3, kind: "voice", es: "Explícale a tu casero que la caldera lleva tres días sin funcionar y convéncele de que mande a alguien esta misma semana.", en: "Tell your landlord the boiler has been broken three days and push for a fix."},
  {phase: 3, kind: "voice", es: "Negocia con tus compañeros de piso un reparto justo de las tareas y de los gastos de comunidad, defendiendo tu propuesta.", en: "Negotiate a fair split of chores and bills with flatmates."},
  {phase: 3, kind: "voice", es: "Cuéntame cómo organizarías un finde con amigos en Madrid con poco presupuesto, y qué harías si empieza a llover.", en: "Plan a low-budget weekend with friends, and adapt if it rains."},
  {phase: 3, kind: "voice", es: "Simula que vas a empadronarte y el funcionario te dice que el contrato de alquiler no vale. Explica cómo reaccionas.", en: "You try to register but your rental contract is rejected. React."},
  {phase: 3, kind: "voice", es: "Explícale a tu compañero de piso, sin montar un pollo, que no ha pagado su parte del alquiler este mes.", en: "Tell your flatmate calmly that they have not paid their share of rent."},
  {phase: 3, kind: "voice", es: "Narra la visita a un piso que quieres alquilar: qué preguntas al casero sobre la fianza, el aval y los gastos.", en: "Narrate a flat viewing and your questions about deposit, guarantor and bills."},
  {phase: 3, kind: "voice", es: "Te han subido el alquiler de golpe. Explica cómo hablarías con el casero para negociar o para decidir mudarte.", en: "Your rent jumped. Explain how you would negotiate or decide to move."},
  {phase: 3, kind: "voice", es: "Cuenta cómo te darías de alta de la luz y el internet en un piso nuevo y qué harías si te cobran mal la primera factura.", en: "Explain setting up electricity and internet and disputing a wrong first bill."},
  {phase: 3, kind: "voice", es: "Simula que llamas al médico de cabecera para pedir cita y te dan una fecha dentro de un mes. Reacciona y busca una solución.", en: "Call for a GP appointment given a slot a month away. React and find a solution."},
  {phase: 3, kind: "voice", es: "Explica a un amigo recién llegado cómo funciona el abono transporte y por qué le conviene el abono joven.", en: "Explain the transport pass to a newcomer and why the youth pass suits them."},
  {phase: 3, kind: "voice", es: "Narra una cena de cañas con compañeros del trabajo en la que tienes que presentarte y encajar en el grupo.", en: "Narrate going for beers with coworkers and fitting into the group."},
  {phase: 3, kind: "voice", es: "Tu compañero de piso hace botellón en casa cada finde y tú tienes que madrugar. Explica cómo planteas el problema.", en: "Your flatmate parties every weekend; you wake up early. Raise the issue."},
  {phase: 3, kind: "voice", es: "Simula que vas al banco a abrir una cuenta y te piden un montón de documentos que no llevas. Cuenta cómo lo gestionas.", en: "Open a bank account but you lack documents. Handle it."},
  {phase: 3, kind: "voice", es: "Explica cómo reclamarías la devolución de la fianza a un casero que dice que hay desperfectos que tú no hiciste.", en: "Claim back your deposit from a landlord alleging damage you did not cause."},
  {phase: 3, kind: "voice", es: "Narra un día en el que se te juntan tres trámites: recoger la TIE, empadronarte y pedir la tarjeta sanitaria.", en: "Narrate a day juggling TIE pickup, registration and health card."},
  {phase: 3, kind: "voice", es: "Tus compañeros quieren hacer un viaje pero cada uno propone algo distinto. Media entre ellos y propón un plan.", en: "Flatmates want different trips; mediate and propose a plan."},
  {phase: 3, kind: "voice", es: "Simula que te has quedado sin llaves a las dos de la mañana y tienes que apañártelas. Cuenta qué haces.", en: "You are locked out at 2am. Narrate how you manage."},
  {phase: 3, kind: "voice", es: "Explica cómo le pedirías a tu jefe en las prácticas que te aclare las condiciones de tu nómina y tu horario.", en: "Ask your internship boss to clarify your payslip and schedule."},
  {phase: 3, kind: "voice", es: "Narra cómo devolverías un producto en una tienda en la que el dependiente te pone pegas y no quiere aceptarlo.", en: "Narrate returning an item to a reluctant shop assistant."},
  {phase: 3, kind: "voice", es: "Tu vecino se queja del ruido pero tú no habías hecho nada. Explica cómo aclaras el malentendido sin discutir.", en: "A neighbour complains of noise you did not make. Clear it up calmly."},
  {phase: 3, kind: "voice", es: "Simula que la agencia inmobiliaria te pide dos meses de fianza y un aval que no tienes. Negocia otra opción.", en: "The agency demands two months deposit and a guarantor you lack. Negotiate."},
  {phase: 3, kind: "voice", es: "Explica cómo organizarías la mudanza a tu piso de Madrid con muebles de segunda mano y sin coche.", en: "Plan moving into your Madrid flat with second-hand furniture and no car."},
  {phase: 3, kind: "voice", es: "Narra una conversación con un compañero de piso al que le toca fregar y siempre lo deja para otro día.", en: "Confront a flatmate who keeps putting off the washing-up."},
  {phase: 3, kind: "voice", es: "Simula que pierdes el metro de vuelta y tienes que decidir entre un taxi caro o esperar el búho. Razona en voz alta.", en: "You miss the last metro; choose between a pricey taxi or the night bus."},
  {phase: 3, kind: "voice", es: "Explica cómo pedirías el certificado de empadronamiento por internet y qué harías si la sede electrónica se cae.", en: "Explain requesting the registration certificate online and coping if the site crashes."},
  {phase: 3, kind: "voice", es: "Tus amigos quieren cenar fuera pero tú estás a dos velas hasta fin de mes. Propón un plan más barato sin quedar mal.", en: "Friends want to eat out but you are broke; propose a cheaper plan gracefully."},
  {phase: 3, kind: "voice", es: "Narra cómo resolverías que te han metido en un grupo de gastos de piso donde alguien no paga nunca.", en: "Resolve a flat-expenses group where one person never pays."},
  {phase: 3, kind: "voice", es: "Simula una llamada a la compañía de internet porque llevas una semana sin conexión y nadie te da soluciones.", en: "Call the internet company after a week with no connection and no answers."},
  {phase: 3, kind: "voice", es: "Explica cómo le contarías a tu familia por videollamada tu primer mes en Madrid, lo bueno y lo que te ha costado.", en: "Tell your family by video call about your first month, the good and the hard."},
  {phase: 3, kind: "voice", es: "Tu casero quiere entrar en el piso sin avisar. Explica cómo le dices, con educación pero firme, que debe avisar antes.", en: "The landlord wants to enter unannounced; tell them firmly to give notice."},
  {phase: 3, kind: "voice", es: "Narra cómo organizarías una cena en el piso para presentar a tus amigos americanos a tus compañeros españoles.", en: "Plan a flat dinner introducing your American and Spanish friends."},
  {phase: 3, kind: "voice", es: "Simula que en la oficina de extranjería te mandan de una ventanilla a otra. Cuenta cómo mantienes la calma y lo resuelves.", en: "You get sent from window to window at immigration. Stay calm and resolve it."},
  {phase: 3, kind: "voice", es: "Explica cómo negociarías con tus compañeros de piso poner la calefacción, que uno quiere ahorrar y otro pasa frío.", en: "Negotiate the heating with flatmates split between saving and being cold."},
  {phase: 3, kind: "voice", es: "Narra un finde de puente en el que planeáis una escapada a la sierra y a última hora falla el coche.", en: "Narrate a long-weekend mountain trip when the car fails last minute."},
  {phase: 3, kind: "voice", es: "Simula que reclamas en el ayuntamiento porque llevas dos meses esperando el empadronamiento y no te llaman.", en: "Complain at the town hall after two months waiting for registration."},
  {phase: 3, kind: "voice", es: "Explica cómo le dirías a un compañero de piso que su pareja prácticamente vive en casa y eso te incomoda.", en: "Tell a flatmate their partner practically lives there and it bothers you."},
  {phase: 3, kind: "voice", es: "Narra cómo devolverías un piso al final del contrato dejándolo todo en orden para recuperar la fianza entera.", en: "Narrate handing back a flat in order to recover the full deposit."},
  {phase: 3, kind: "voice", es: "Simula que te equivocas de línea en el metro con prisa y tienes que preguntar y reorganizarte sobre la marcha.", en: "You take the wrong metro line in a rush; ask and reroute on the fly."},
  {phase: 3, kind: "voice", es: "Explica cómo convencerías a tu casero de que te deje pintar la habitación o poner tus muebles.", en: "Convince your landlord to let you paint the room or add furniture."},
  {phase: 3, kind: "voice", es: "Tus compañeros de piso quieren meter a un cuarto inquilino y a ti no te convence. Defiende tu postura.", en: "Flatmates want a fourth tenant; you are unconvinced. Defend your view."},
  {phase: 3, kind: "voice", es: "Narra cómo gestionarías que se ha inundado el baño del piso y el casero no coge el teléfono.", en: "The bathroom floods and the landlord will not pick up. Handle it."},
  {phase: 3, kind: "voice", es: "Simula que en el bar te cobran de más en una ronda de cañas para el grupo. Aclara la cuenta sin montar numerito.", en: "You are overcharged for a round of beers; sort the bill without a scene."},
  {phase: 3, kind: "voice", es: "Explica cómo te organizarías para compaginar el curro, las clases de español y la vida social en Madrid sin quemarte.", en: "Explain balancing work, Spanish classes and social life in Madrid without burning out."},

  // ============================================================
  // PHASE 3 — GLIGLISH (bureaucracy, flat, bank, bar, SIM, gym, pickup)
  // ============================================================
  {phase: 3, kind: "gliglish", es: "vengo a por la cita del NIE; aquí tiene el justificante; ¿qué documentos faltan?", en: "Attend an immigration appointment for your NIE."},
  {phase: 3, kind: "gliglish", es: "quería ver el piso; ¿cuánto es la fianza?; ¿los gastos van aparte?", en: "View a flat and ask about deposit and bills."},
  {phase: 3, kind: "gliglish", es: "tenemos que hablar de la limpieza; no me parece justo; propongo turnos", en: "Raise a chores conflict with a flatmate and propose a rota."},
  {phase: 3, kind: "gliglish", es: "quería abrir una cuenta; soy estudiante extranjero; ¿qué necesito?", en: "Open a bank account as a foreign student."},
  {phase: 3, kind: "gliglish", es: "ponme dos cañas y una de bravas; ¿me oyes?; ¿cuánto es?", en: "Order over the noise in a loud, busy bar."},
  {phase: 3, kind: "gliglish", es: "quería una tarjeta SIM; con datos; ¿necesito el pasaporte?", en: "Buy a SIM card and ask what you need."},
  {phase: 3, kind: "gliglish", es: "quería apuntarme al gimnasio; ¿hay tarifa de estudiante?; ¿permanencia?", en: "Sign up at a gym and ask about student rates and contracts."},
  {phase: 3, kind: "gliglish", es: "vengo a recoger un paquete; aquí está el aviso; mi DNI es este", en: "Pick up a package at the collection point."},
  {phase: 3, kind: "gliglish", es: "vengo a empadronarme; traigo el contrato; ¿me dan el certificado hoy?", en: "Register at the town hall and ask for your certificate."},
  {phase: 3, kind: "gliglish", es: "quería recargar el abono joven; treinta días; ¿me ayudas con la máquina?", en: "Top up the youth transport pass and ask for help."},
  {phase: 3, kind: "gliglish", es: "la nevera hace un ruido raro; lleva días; ¿puede venir el técnico?", en: "Report a broken appliance to your landlord by phone."},
  {phase: 3, kind: "gliglish", es: "quería darme de alta de la luz; piso nuevo; ¿cuándo la activáis?", en: "Set up the electricity in your name for a new flat."},
  {phase: 3, kind: "gliglish", es: "necesito pedir cita para la tarjeta sanitaria; soy nuevo aquí; ¿en qué centro?", en: "Ask how to get a public health card as a newcomer."},
  {phase: 3, kind: "gliglish", es: "somos seis para cenar; ¿tenéis mesa?; ¿ponéis menú del día?", en: "Get a table for a group and ask about the set menu."},
  {phase: 3, kind: "gliglish", es: "oye, tu pareja está aquí todos los días; no me va bien; hablémoslo", en: "Address a flatmate about their partner always being over."},
  {phase: 3, kind: "gliglish", es: "quería reclamar la fianza; dejé el piso bien; ¿cuándo me la devolvéis?", en: "Claim back your deposit after moving out."},
  {phase: 3, kind: "gliglish", es: "perdona, ¿este trámite es aquí?; me han mandado de otra ventanilla; ¿número?", en: "Navigate being sent between windows at a government office."},
  {phase: 3, kind: "gliglish", es: "quería un doble y una tapa; para la barra; ¿qué tapa entra?", en: "Order a beer and free tapa standing at the bar."},
  {phase: 3, kind: "gliglish", es: "se me ha ido internet; llevo días sin conexión; ¿me mandáis un técnico?", en: "Call your provider about a days-long internet outage."},
  {phase: 3, kind: "gliglish", es: "quería devolver esto; está sin usar; tengo el ticket; ¿me lo abonáis?", en: "Return a purchase and insist on a refund."},
  {phase: 3, kind: "gliglish", es: "buenas, tengo cita a las diez; para la TIE; ¿es esta cola?", en: "Arrive for your TIE card appointment and find the right queue."},
  {phase: 3, kind: "gliglish", es: "necesitamos repartir los gastos; luz, agua y comunidad; ¿a partes iguales?", en: "Agree with flatmates on how to split the bills."},
  {phase: 3, kind: "gliglish", es: "quería contratar internet para casa; ¿fibra?; ¿cuánto tarda la instalación?", en: "Set up home internet and ask about installation time."},
  {phase: 3, kind: "gliglish", es: "perdona, ¿me cambias de habitación?; hay mucho ruido; da a la calle", en: "Ask to swap rooms in a shared flat due to street noise."},
  {phase: 3, kind: "gliglish", es: "quería pedir cita previa; para el NIE; ¿no hay huecos?; ¿aviso si sale?", en: "Try to book a scarce cita previa slot and ask about waitlists."}
];
